# Generated by Django 4.2 on 2023-11-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficina', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'oficina',
                'verbose_name_plural': 'oficina',
            },
        ),
    ]
