# Generated by Django 5.0 on 2023-12-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbconsejomunicipal',
            old_name='sigla_unidad',
            new_name='nombre_cargo',
        ),
    ]
