# Generated by Django 5.0 on 2023-12-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondencia',
            options={'verbose_name': 'correspondencia', 'verbose_name_plural': 'correspondencias'},
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='asunto_archivado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
