
# Generated by Django 4.2 on 2023-12-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_remitente', models.CharField(max_length=200)),
                ('of_remitente', models.CharField(max_length=200)),
                ('car_remitente', models.CharField(max_length=200)),
                ('user_destinatario', models.CharField(max_length=200)),
                ('asunto_hr', models.CharField(max_length=200)),
                ('num_fojas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'enviado',
                'verbose_name_plural': 'enviados',
            },
        ),
        migrations.AlterModelOptions(
            name='bandeja',
            options={'verbose_name': 'bandeja', 'verbose_name_plural': 'bandeja'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name': 'oficina', 'verbose_name_plural': 'oficinas'},
        ),
    ]
