# Generated by Django 5.0 on 2023-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandeja',
            name='recibido',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
