# Generated by Django 5.0 on 2023-12-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandeja',
            name='fecha_recibido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
