# Generated by Django 5.0 on 2024-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crrconsejomunicipal',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
