# Generated by Django 5.0 on 2024-01-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_alter_crrconsejomunicipal_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='codigo',
            field=models.IntegerField(default=100),
        ),
    ]
