# Generated by Django 5.0 on 2024-01-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_alter_correspondencia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
