# Generated by Django 5.0 on 2024-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_correspondencia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
