# Generated by Django 5.0 on 2023-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_alter_enviado_asunto_hr_alter_enviado_car_remitente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandeja',
            name='asunto_hoja_ruta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='cargo_destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='cargo_remitente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='correspondencia_archivado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='correspondencia_cancelada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='correspondencia_derivada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='correspondencia_devuelta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='correspondencia_devuelto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='correspondencia_recibido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='fecha_derivado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='numero_fojas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='oficina_destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='oficina_remitente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='tipo_hoja_ruta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='usuario_destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='usuario_remitente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
