# Generated by Django 5.0 on 2023-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0005_rename_correspondencia_cancelada_bandeja_correspondencia_cancelado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandeja',
            old_name='correspondencia_archivado',
            new_name='archivado',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='cargo_remitente',
            new_name='asunto_cancelado',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='observacion_cancelado',
            new_name='asunto_devuelto',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='correspondencia_cancelado',
            new_name='cancelado',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='observacion_devuelto',
            new_name='cargo_rtte',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='codigo_hoja_ruta',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='correspondencia_derivado',
            new_name='derivado',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='correspondencia_devuelto',
            new_name='devuelto',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='oficina_remitente',
            new_name='nombre_rtte',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='usuario_remitente',
            new_name='oficina_rtte',
        ),
        migrations.RenameField(
            model_name='bandeja',
            old_name='correspondencia_recibido',
            new_name='pendiente',
        ),
        migrations.AddField(
            model_name='bandeja',
            name='recibido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bandeja',
            name='usuario_rtte',
            field=models.CharField(blank=True, default='S/C', max_length=20, null=True),
        ),
    ]
