# Generated by Django 5.0 on 2023-12-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0006_rename_correspondencia_archivado_bandeja_archivado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandeja',
            name='nombre_destno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
