# Generated by Django 5.0 on 2023-12-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0007_bandeja_nombre_destno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandeja',
            old_name='nombre_destno',
            new_name='nombre_destino',
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='fecha_derivado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
