# Generated by Django 5.0 on 2023-12-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0009_alter_bandeja_usuario_rtte'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviado',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
