# Generated by Django 4.2 on 2023-11-10 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficina',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficina', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficina',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/image_user.png', upload_to='users/')),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='accounts.cargo')),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oficina', to='accounts.oficina')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['id'],
            },
        ),
    ]
